// Mock data for testing without Supabase

// Super Admin Profile
export const mockProfileSuperAdmin = {
  id: 'demo-user-super',
  email: 'admin@loyaltypass.com',
  full_name: 'Super Admin',
  role: 'super_admin' as const,
  business_id: null,
  phone_number: '+968 9000 0000',
  avatar_url: null,
  is_active: true,
}

// Business Admin Profile (Coffee Paradise)
export const mockProfileBusinessAdmin = {
  id: 'demo-user-business',
  email: 'business@coffeeparadise.com',
  full_name: 'Coffee Shop Owner',
  role: 'business_admin' as const,
  business_id: 'demo-business-1',
  phone_number: '+968 9111 1111',
  avatar_url: null,
  is_active: true,
}

// Staff Profile
export const mockProfileStaff = {
  id: 'demo-user-staff',
  email: 'staff@coffeeparadise.com',
  full_name: 'John Smith',
  role: 'staff' as const,
  business_id: 'demo-business-1',
  phone_number: '+968 9444 4444',
  avatar_url: null,
  is_active: true,
}

// Default profile (business admin for easy testing)
export const mockProfile = mockProfileBusinessAdmin

export const mockBusinesses = [
  {
    id: 'demo-business-1',
    name: 'Coffee Paradise',
    slug: 'coffee-paradise',
    logo_url: null,
    brand_color: '#8B4513',
    phone_number: '+968 9111 1111',
    email: 'contact@coffeeparadise.com',
    address: 'Muscat, Oman',
    description: 'Best coffee in town',
    is_active: true,
    self_service_enabled: false,
    owner_user_id: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'demo-business-2',
    name: 'Fresh Bakery',
    slug: 'fresh-bakery',
    logo_url: null,
    brand_color: '#FFD700',
    phone_number: '+968 9222 2222',
    email: 'info@freshbakery.com',
    address: 'Salalah, Oman',
    description: 'Fresh bread daily',
    is_active: true,
    self_service_enabled: false,
    owner_user_id: null,
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'demo-business-3',
    name: 'Style Salon',
    slug: 'style-salon',
    logo_url: null,
    brand_color: '#FF69B4',
    phone_number: '+968 9333 3333',
    email: 'booking@stylesalon.com',
    address: 'Nizwa, Oman',
    description: 'Hair and beauty services',
    is_active: false,
    self_service_enabled: false,
    owner_user_id: null,
    created_at: '2024-02-01T00:00:00Z',
    updated_at: '2024-02-01T00:00:00Z',
  },
]

export const mockCustomers = [
  {
    id: 'demo-customer-1',
    business_id: 'demo-business-1',
    phone_number: '+968 9111 1111',
    full_name: 'Ahmed Al-Said',
    birthday: '1990-05-15',
    gender: 'male',
    notes: 'Prefers cappuccino',
    total_visits: 23,
    total_points: 450,
    total_spent: 230,
    membership_tier: 'gold',
    qr_code: 'QR-AHMED-123',
    wallet_card_url: null,
    is_active: true,
    created_at: '2024-01-10T00:00:00Z',
    updated_at: '2024-06-10T00:00:00Z',
  },
  {
    id: 'demo-customer-2',
    business_id: 'demo-business-1',
    phone_number: '+968 9222 2222',
    full_name: 'Fatima Al-Balushi',
    birthday: '1995-08-20',
    gender: 'female',
    notes: 'Allergic to nuts',
    total_visits: 45,
    total_points: 890,
    total_spent: 445,
    membership_tier: 'vip',
    qr_code: 'QR-FATIMA-456',
    wallet_card_url: null,
    is_active: true,
    created_at: '2024-01-05T00:00:00Z',
    updated_at: '2024-06-12T00:00:00Z',
  },
  {
    id: 'demo-customer-3',
    business_id: 'demo-business-1',
    phone_number: '+968 9333 3333',
    full_name: 'Mohammed Al-Harthi',
    birthday: null,
    gender: 'male',
    notes: null,
    total_visits: 8,
    total_points: 120,
    total_spent: 80,
    membership_tier: 'silver',
    qr_code: 'QR-MOHAMMED-789',
    wallet_card_url: null,
    is_active: true,
    created_at: '2024-03-15T00:00:00Z',
    updated_at: '2024-06-11T00:00:00Z',
  },
]

export const mockLoyaltyPrograms = [
  {
    id: 'demo-program-1',
    business_id: 'demo-business-1',
    name: 'Buy 5 Get 1 Free',
    description: 'Purchase 5 coffees and get your 6th one free!',
    type: 'visit_based' as const,
    required_visits: 5,
    points_per_currency: null,
    points_for_reward: null,
    required_stamps: null,
    cashback_percentage: null,
    reward_name: 'Free Coffee',
    reward_description: 'One free coffee of any size',
    reward_value: 5,
    is_active: true,
    start_date: '2024-01-01',
    end_date: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'demo-program-2',
    business_id: 'demo-business-1',
    name: 'Points Rewards',
    description: 'Earn 1 point for every OMR spent',
    type: 'points_based' as const,
    required_visits: null,
    points_per_currency: 1,
    points_for_reward: 100,
    required_stamps: null,
    cashback_percentage: null,
    reward_name: 'Free Pastry',
    reward_description: 'Choose any pastry from our selection',
    reward_value: 3,
    is_active: true,
    start_date: '2024-01-01',
    end_date: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
]

export const mockRewards = [
  {
    id: 'demo-reward-1',
    business_id: 'demo-business-1',
    customer_id: 'demo-customer-1',
    loyalty_program_id: 'demo-program-1',
    reward_name: 'Free Coffee',
    reward_description: 'One free coffee of any size',
    reward_value: 5,
    is_redeemed: false,
    earned_date: '2024-06-10T10:00:00Z',
    redeemed_date: null,
    redeemed_by: null,
    expiry_date: null,
    created_at: '2024-06-10T10:00:00Z',
    customers: {
      phone_number: '+968 9111 1111',
      full_name: 'Ahmed Al-Said',
    },
    loyalty_programs: {
      name: 'Buy 5 Get 1 Free',
    },
  },
  {
    id: 'demo-reward-2',
    business_id: 'demo-business-1',
    customer_id: 'demo-customer-2',
    loyalty_program_id: 'demo-program-2',
    reward_name: 'Free Pastry',
    reward_description: 'Choose any pastry from our selection',
    reward_value: 3,
    is_redeemed: false,
    earned_date: '2024-06-11T14:30:00Z',
    redeemed_date: null,
    redeemed_by: null,
    expiry_date: null,
    created_at: '2024-06-11T14:30:00Z',
    customers: {
      phone_number: '+968 9222 2222',
      full_name: 'Fatima Al-Balushi',
    },
    loyalty_programs: {
      name: 'Points Rewards',
    },
  },
]

export const mockInvoices = [
  {
    id: 'demo-invoice-1',
    business_id: 'demo-business-1',
    subscription_id: 'demo-sub-1',
    invoice_number: 'INV-202406-0001',
    amount: 79,
    status: 'paid' as const,
    issue_date: '2024-06-01',
    due_date: '2024-06-15',
    paid_date: '2024-06-05',
    notes: null,
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2024-06-05T00:00:00Z',
    businesses: {
      name: 'Coffee Paradise',
    },
  },
  {
    id: 'demo-invoice-2',
    business_id: 'demo-business-2',
    subscription_id: 'demo-sub-2',
    invoice_number: 'INV-202406-0002',
    amount: 29,
    status: 'pending' as const,
    issue_date: '2024-06-01',
    due_date: '2024-06-15',
    paid_date: null,
    notes: null,
    created_at: '2024-06-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
    businesses: {
      name: 'Fresh Bakery',
    },
  },
]

export const mockStaff = [
  {
    id: 'demo-staff-1',
    email: 'john@coffeeparadise.com',
    full_name: 'John Smith',
    role: 'staff' as const,
    business_id: 'demo-business-1',
    phone_number: '+968 9444 4444',
    avatar_url: null,
    is_active: true,
    created_at: '2024-02-01T00:00:00Z',
    updated_at: '2024-02-01T00:00:00Z',
  },
  {
    id: 'demo-staff-2',
    email: 'sara@coffeeparadise.com',
    full_name: 'Sara Al-Balushi',
    role: 'staff' as const,
    business_id: 'demo-business-1',
    phone_number: '+968 9555 5555',
    avatar_url: null,
    is_active: true,
    created_at: '2024-02-15T00:00:00Z',
    updated_at: '2024-02-15T00:00:00Z',
  },
]

export const isDemoMode = () => {
  const supabaseUrl = import.meta.env.VITE_SUPABASE_URL
  return !supabaseUrl || supabaseUrl.includes('your-project') || supabaseUrl === 'https://your-project.supabase.co'
}
